"""Type stubs for qdarkstyle"""

def load_stylesheet() -> str: ...
def load_stylesheet_pyqt5() -> str: ...
def load_stylesheet_pyqt6() -> str: ...
def load_stylesheet_pyside6() -> str: ...
def load_stylesheet_from_environment() -> str: ...

# Constants
REPO_URL: str
EXAMPLE_PATH: str
STYLES_PATH: str

# Version info
__version__: str
__version_info__: tuple
