[tool.pyright]
typeCheckingMode = "off"
reportMissingImports = "none"
reportMissingTypeStubs = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportGeneralTypeIssues = "none"
reportOptionalMemberAccess = "none"
reportOptionalSubscript = "none"
reportOptionalCall = "none"
reportOptionalIterable = "none"
reportOptionalContextManager = "none"
reportOptionalOperand = "none"
reportAttributeAccessIssue = "none"
reportRedeclaration = "none"
reportUnboundVariable = "none"
reportUndefinedVariable = "none"
reportAssignmentType = "none"
reportArgumentType = "none"
reportReturnType = "none"
reportMissingTypeArgument = "none"
reportCallIssue = "none"
reportIndexIssue = "none"
reportOperatorIssue = "none"
reportInconsistentConstructor = "none"
pythonVersion = "3.8"
pythonPlatform = "Windows"

[tool.pylance]
typeCheckingMode = "off"

[tool.pylint]
disable = "all"

[tool.mypy]
ignore_errors = true
ignore_missing_imports = true
no_implicit_optional = false
strict_optional = false
warn_redundant_casts = false
warn_unused_ignores = false
warn_return_any = false
warn_unreachable = false
allow_untyped_globals = true
allow_redefinition = true
allow_untyped_defs = true
allow_incomplete_defs = true
allow_untyped_calls = true
allow_untyped_decorators = true

[tool.black]
line-length = 200
skip-string-normalization = true

[tool.isort]
line_length = 200
skip_gitignore = true

[tool.ruff]
ignore = ["E", "W", "F", "C", "N", "D", "I", "S", "B", "A", "COM", "ISC", "ICN", "T", "Q", "RET", "SIM", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "TRY", "NPY", "RUF"]
line-length = 200
target-version = "py38"