"""Type stubs for qdarkstyle"""

def load_stylesheet() -> str: ...
def load_stylesheet_pyqt5() -> str: ...
def load_stylesheet_pyqt6() -> str: ...
def load_stylesheet_pyside2() -> str: ...
def load_stylesheet_pyside6() -> str: ...
def load_stylesheet_from_environment() -> str: ...
